## Why Use Numpy??
1) Numpy provides efficient storage
2) provides better ways of handeling data for processing
3) It is fast
4) uses relatively less memory

In [418]:
import numpy as np

### Array creation: conversion from the python structures


In [419]:
list = [1,2,3,4,5]
arr = np.array(list)
type(arr)

numpy.ndarray

In [420]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])
print(f"Shape of array is {arr1.shape}")
arr1

Shape of array is (3, 5)


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [421]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [422]:
listarray.shape

(3, 3)

In [423]:
listarray.size

9

### Array creation with all zeros

In [424]:
# Creates array with dimention 2x7 with all zero elements
zero = np.zeros((2,5))      
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [425]:
zero.shape

(2, 5)

In [426]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [427]:
# generates an array with four evenly spaced values between 1 and 5 (both inclusive). The values are distributed in such a way that they are linearly spaced.
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [428]:
# Creates array of size 2x4 of random numbers
emp = np.empty((2,4))
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 2.37151510e-321, 6.95314361e-310,
        7.76650459e-312]])

In [429]:
# Creates array of size same as lspace
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [430]:
# Gives identity matrix of dimensions 5x5
ide = np.identity(5)
print(f"Shape of matrix is {ide.shape}")
ide

Shape of matrix is (5, 5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [431]:
new = np.arange(99)
new 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [432]:
new.reshape((3,33))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [433]:
new.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [434]:
56.17-32 

24.17

### Create random int array

In [435]:
# Create random integer array in range 10 to 50 of size 4
np.random.randint(10,50,4)

array([14, 32, 16, 28])

In [436]:
np.random.randint(10,50,4).reshape(2,2)

array([[30, 39],
       [29, 15]])

In [437]:
# The np.random.randn(5, 6) command generates a 2D NumPy array with dimensions 5x6, where each element is drawn from a standard normal distribution (mean = 0, standard deviation = 1).

np.random.randn(5,6)

array([[ 0.01439365,  0.02718804, -0.41415428, -0.0212025 ,  1.22378905,
         2.14990725],
       [-0.96122246, -0.33590562,  1.14336938,  1.99988453,  0.72882055,
         1.03834711],
       [ 0.86963095, -0.09966798, -1.07188945,  0.81061547, -0.09893399,
         2.45274839],
       [ 0.72403544,  0.67425175,  0.49671369, -0.82613109,  0.07978113,
         0.01955216],
       [ 0.24068613,  1.36394318, -1.05395469, -0.05404496,  0.47544934,
         2.2894805 ]])

In [438]:
# command generates a 2D NumPy array with dimensions 4x7, where each element is drawn from a uniform distribution over the interval [0.0, 1.0).

np.random.random_sample((4,4))

array([[0.99445542, 0.98968034, 0.09355051, 0.47921985],
       [0.14030773, 0.81423727, 0.57342216, 0.31233459],
       [0.37221496, 0.28538186, 0.51069213, 0.58597952],
       [0.72730923, 0.9089764 , 0.54190439, 0.35476592]])

### Numpy axis

In [439]:
a1 = np.array([[1,2,3],
               [5,6,7]])

In [440]:
sum0 = a1.sum(axis=0)
sum0

array([ 6,  8, 10])

In [441]:
sum1 = a1.sum(axis=1)
sum1 

array([ 6, 18])

In [442]:
# For doing traspose of the given matrix
a1.T

array([[1, 5],
       [2, 6],
       [3, 7]])

In [443]:
a1.flat
print(a1.flat)

for i in a1.flat:
    print(i)

1
2
3
5
6
7


In [444]:
one = np.array([1,22,3,4,5,76])

In [445]:
# gives index where maximum index is present
one.argmax()

5

In [446]:
# gives index where minimum index is present
one.argmin()

0

In [447]:
# Gives us the indices according to the sorting order for each element
one.argsort()  

array([0, 2, 3, 4, 1, 5], dtype=int64)

### Mathematical operations on array

In [448]:
a1

array([[1, 2, 3],
       [5, 6, 7]])

In [449]:
a2 = np.array([[1,2,3],
               [2,3,4]])

In [450]:
a1 + a2

array([[ 2,  4,  6],
       [ 7,  9, 11]])

In [451]:
a1 - a2

array([[0, 0, 0],
       [3, 3, 3]])

In [452]:
a1 *a2 

array([[ 1,  4,  9],
       [10, 18, 28]])

In [453]:
a1/a2

array([[1.  , 1.  , 1.  ],
       [2.5 , 2.  , 1.75]])

In [454]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131]])

In [455]:
a1.sum()

24

In [456]:
a1.max()

7

In [457]:
a1.min()

1

## find elements from array

In [458]:
arr2 = np.array([[1,2,3,4],
                [2,5,6,7],
                [6,7,8,9]])
arr2

array([[1, 2, 3, 4],
       [2, 5, 6, 7],
       [6, 7, 8, 9]])

In [459]:
np.where(arr2>3) 
# In this output, the first array represents the row indices, and the second array represents the column indices. So, the elements at positions (0, 3), (1, 1), (1, 2), (2, 0), (2, 1), and (2, 2) in the original array are greater than 3.

(array([0, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([3, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

### size comparision of numpy and list

In [460]:
import sys

In [461]:
py_arr = [1,2,3,4]
np_arr = np.array(py_arr)

In [462]:
sys.getsizeof(1) * len(py_arr)

112

In [463]:
np_arr.itemsize * np_arr.size

16